name: Phoenix Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: # Set the  cron for daily midnight IST
    - cron: "30 18 * *  *" # This is UTC time 

  workflow_dispatch:
    inputs:
     env:
        description: "Environment"
        type: choice
        options: [qa,dev,uat]
        default: qa
        required: true
    
     suiteXmlFile:
        description: "TestNG xml files for different testing methods/sets"
        type: choice
        options: [testng.xml,smoke.xml,regression.xml]
        default: testng.xml
        required: true
  
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

        
    - name: Execute Test Automation Framework
      run: mvn clean test -DsuiteXmlFile="${{ github.event.inputs.suiteXmlFile }}" -Denv="${{ github.event.inputs.env }}"

    # Added details from Upload a Build Artifact 
    - name: Upload a Build Artifact
      if: always()                         # Create reports even if tests fail
      uses: actions/upload-artifact@v6.0.0
      with:
         name: Surefire Report
         path: target/surefire-reports/
         retention-days: 10
